### ISSUE TITLE
Suggestion: shorter name and publish to bower/npm

### ISSUE THREAD

**Issue by tomwayson** [thollingsheadesri/arcgis-server-store#12]
I suggest publishing this to at least bower's repository and possibly npm as well. I can make a PR for this if you are interested, however, before I do, I suggest using a shorter name (like 'arcgis-server-store', or 'dojo-arcgis-server-store').

**Comment by btfou** [comment]
+1 bower

**Comment by thollingsheadesri** [comment]
Thanks for the suggestions. I have renamed to *arcgis-server-store*, and published to npm and bower.

**Comment by tomwayson** [comment]
Awesome! Installed perfectly, thanks @thollingsheadesri.
