### ISSUE TITLE
Support querying where "ATTRIBUTE IS NULL"

### ISSUE THREAD

**Issue by gavinr** [thollingsheadesri/arcgis-server-store#15]
Right now if i do:
`agsStore.query({'my_column':'null'})`, the request that gets generated is:
`where:my_column = 'null'`

I would like it to send out:
`where:my_column IS NULL`

Let me know your thoughts. I'm happy to create a PR.

**Comment by tomwayson** [comment]
seems like the most reasonable behavior to me

**Comment by btfou** [comment]
@gavinr Consider something for `where:my_column IS NOT NULL` as well if you PR for this.

**Comment by gavinr** [comment]
@btfou that is interesting. How are "not equal" cases be handed currently? (maybe a question for @thollingsheadesri) ... I guess we should follow that pattern.

**Comment by thollingsheadesri** [comment]
@gavinr Note that you could do the following instead:

```
var q = new Query();
q.where = 'my_column IS NOT NULL';
agsStore.query(q);
```

However I agree that it would be nice to have `agsStore.query({'my_column':null})` resolve to `where: my_column IS NULL` and `agsStore.query({'my_column':'null'})` resolve to `where: my_column = 'null'`.

If you are interested in creating a PR, you will need to look at [_objectToQuery](https://github.com/thollingsheadesri/arcgis-server-store/blob/master/ArcGISServerStore.js#L500).

**Comment by thollingsheadesri** [comment]
@btfou @gavinr The current implementation was meant to replicate querying with an object hash as provided by the [SimpleQueryEngine](https://dojotoolkit.org/reference-guide/1.10/dojo/store/util/SimpleQueryEngine.html#dojo-store-util-simplequeryengine). I don't believe the SimpleQueryEngine supports "not equal" cases.

Do you have a good suggestion on how to indicate a "not equal" query?

**Comment by tomwayson** [comment]
I would say if it's not already in SimpleQueryEngine, no need to add it here

**Comment by btfou** [comment]
@thollingsheadesri You're right about that. Constructing a `Query().where` clause is what I've been doing from inputs and various props for complex queries including several is and is not null. When I saw this, I thought an object hash would simplify things.
