### ISSUE TITLE
Allow passing of function to Query

### ISSUE THREAD

**Issue by gavinr** [thollingsheadesri/arcgis-server-store#18]
When using grids, it's a standard use case to pass a function to "query" - and that function gets passed to the store. Right now, arcgis-server-store does not support this workflow (because you would probably need all the data for the store on the front-end ... so this issue may be related to #17)

**Comment by tomwayson** [comment]
I *think* that use case is for client-side stores only.

For example, [dojo/store/JsonRest.query()](https://dojotoolkit.org/api/?qs=1.10/dojo/store/JsonRest#1_10dojo_store_JsonRest_query) does not appear to support passing a function.

**Comment by gavinr** [comment]
agreed!
